# Generated by Django 6.0.6 on 2026-06-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_position',
            field=models.IntegerField(default=50, help_text='50 — строго по центру. 0 — показать самый верх кадра, 100 — показать самый низ.', verbose_name='Центрирование фото по вертикали (от 0 - верх, до 100 - низ)'),
        ),
    ]
