# Generated by Django 6.0.6 on 2026-06-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_position',
            field=models.IntegerField(default=50, help_text='Настройка фокуса для этой конкретной картинки в галерее.', verbose_name='Центрирование этого фото по вертикали (0 - верх, 100 - низ)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_position',
            field=models.IntegerField(default=50, help_text='50 — строго по центру.', verbose_name='Центрирование главного фото по вертикали (0 - верх, 100 - низ)'),
        ),
    ]
