# Generated by Django 6.0.6 on 2026-06-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productimage_image_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderNavigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название пункта меню')),
                ('link', models.CharField(default='#', max_length=200, verbose_name='Ссылка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Пункт меню навигации',
                'verbose_name_plural': 'Ссылки навигации шапки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeaderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='LUMORA', max_length=50, verbose_name='Название бренда')),
                ('logo_icon', models.CharField(default='✿', max_length=10, verbose_name='Символ логотипа')),
                ('promo_text', models.CharField(default='🔥 Скидка 20% на первый заказ!', max_length=200, verbose_name='Промо-текст')),
            ],
            options={
                'verbose_name': 'Настройки шапки',
                'verbose_name_plural': 'Настройки шапки',
            },
        ),
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(default='New Season Collection', max_length=100, verbose_name='Малый надзаголовок')),
                ('title', models.CharField(default='Live Beautifully. Shop Effortlessly.', max_length=200, verbose_name='Главный заголовок')),
                ('description', models.TextField(verbose_name='Описание (подзаголовок)')),
                ('button_text', models.CharField(default='Shop Now', max_length=50, verbose_name='Текст кнопки')),
                ('button_link', models.CharField(default='#catalog-section', max_length=200, verbose_name='Ссылка с кнопки')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Иллюстрация справа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен на сайте')),
            ],
            options={
                'verbose_name': 'Главный баннер',
                'verbose_name_plural': 'Главный баннер',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='image_position',
            field=models.IntegerField(default=50, help_text='50 — строго по центру.', verbose_name='Центрирование главного фото по vertical (0 - верх, 100 - низ)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_position',
            field=models.IntegerField(default=50, verbose_name='Центрирование этого фото по вертикали'),
        ),
    ]
