# Generated by Django 6.0.6 on 2026-06-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_headernavigation_headersettings_mainbanner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headernavigation',
            name='link',
            field=models.CharField(default='#', max_length=200, verbose_name='Ссылка (URL)'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='logo_icon',
            field=models.CharField(default='✿', max_length=10, verbose_name='Иконка логотипа'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Иллюстрация справа (веточка/модель)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_position',
            field=models.IntegerField(default=50, verbose_name='Центрирование главного фото'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_position',
            field=models.IntegerField(default=50, verbose_name='Центрирование фото'),
        ),
    ]
