# Generated by Django 6.0.6 on 2026-06-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_headernavigation_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBlockSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_title', models.CharField(default='Shop by Category', max_length=100, verbose_name='Заголовок блока')),
                ('browse_all_text', models.CharField(default='Browse all →', max_length=50, verbose_name='Текст ссылки')),
                ('browse_all_link', models.CharField(default='#', max_length=200, verbose_name="Ссылка 'Смотреть все'")),
            ],
            options={
                'verbose_name': 'Настройки блока категорий',
                'verbose_name_plural': 'Настройки блока категорий',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Если не загружено, возьмется фото первого товара', null=True, upload_to='categories/', verbose_name='Кастомное фото/иконка для главной'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Поставьте галочку, чтобы категория появилась в блоке 'Shop by Category'", verbose_name='Подсветить на главной'),
        ),
        migrations.AlterField(
            model_name='headernavigation',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок sorting'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Иллюстрация справа'),
        ),
    ]
