# Generated by Django 6.0.6 on 2026-06-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_categoryblocksettings_category_icon_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_position',
            field=models.IntegerField(default=50, help_text='Настройка фокуса для круглой плашки на главной.', verbose_name='Центрирование фото по вертикали (0 - верх, 100 - низ)'),
        ),
        migrations.AlterField(
            model_name='headernavigation',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
    ]
