# Generated by Django 6.0.6 on 2026-06-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_category_icon_position_alter_headernavigation_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbanner',
            name='payment_subtitle',
            field=models.CharField(default='100% protected', max_length=100, verbose_name='Подзаголовок оплаты'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='payment_title',
            field=models.CharField(default='Secure Payment', max_length=100, verbose_name='Заголовок оплаты'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='shipping_subtitle',
            field=models.CharField(default='On orders over $50', max_length=100, verbose_name='Подзаголовок доставки'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='shipping_title',
            field=models.CharField(default='Free Shipping', max_length=100, verbose_name='Заголовок доставки'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='show_payment_badge',
            field=models.BooleanField(default=True, verbose_name='Показывать плашку оплаты'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='show_shipping_badge',
            field=models.BooleanField(default=True, verbose_name='Показывать плашку доставки'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='button_text',
            field=models.CharField(default='Купить', max_length=50, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='sub_title',
            field=models.CharField(default='Новая коллекция', max_length=100, verbose_name='Малый надзаголовок'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='title',
            field=models.CharField(default='Live Beautifully', max_length=200, verbose_name='Главный заголовок'),
        ),
    ]
