# Generated by Django 6.0.6 on 2026-06-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_mainbanner_payment_subtitle_mainbanner_payment_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.CharField(default='✦ LIMITED TIME OFFER', max_length=100, verbose_name='Малый верхний тег')),
                ('title', models.CharField(default='Spring Sale is Live!', max_length=200, verbose_name='Главный заголовок')),
                ('description', models.TextField(default='Enjoy up to 40% off on selected items and seasonal interior essentials.', verbose_name='Описание баннера')),
                ('badge_up_to_text', models.CharField(default='UP TO', max_length=20, verbose_name='Надпись над скидкой')),
                ('badge_value_text', models.CharField(default='40%', max_length=20, verbose_name='Размер скидки')),
                ('badge_bottom_text', models.CharField(default='OFF', max_length=20, verbose_name='Надпись под скидкой')),
                ('button_text', models.CharField(default='EXPLORE DEALS', max_length=50, verbose_name='Текст кнопки')),
                ('button_link', models.CharField(default='#', max_length=200, verbose_name='Ссылка кнопки')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promo/', verbose_name='Изображение интерьера справа')),
                ('is_active', models.BooleanField(default=True, help_text='Если снять галочку, баннер полностью пропадет с главной страницы', verbose_name='Активен на сайте')),
            ],
            options={
                'verbose_name': 'Промо-баннер распродажи',
                'verbose_name_plural': 'Промо-баннер распродажи',
            },
        ),
    ]
