# Generated by Django 6.0.6 on 2026-06-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_promobanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Кастомное фото/иконка для главной'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_position',
            field=models.IntegerField(default=50, verbose_name='Центрирование фото по вертикали (0 - верх, 100 - низ)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Подсветить на главной'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен на сайте'),
        ),
        migrations.CreateModel(
            name='FeaturedProductsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_title', models.CharField(default='New Arrivals', max_length=100, verbose_name='Заголовок блока')),
                ('view_all_text', models.CharField(default='View all →', max_length=50, verbose_name='Текст ссылки')),
                ('view_all_link', models.CharField(default='/catalog/', max_length=200, verbose_name='Ссылка на кнопке')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать блок на сайте')),
                ('products', models.ManyToManyField(blank=True, related_name='featured_sections', to='shop.product', verbose_name='Товары для отображения')),
            ],
            options={
                'verbose_name': 'Витрина топ-товаров на главной',
                'verbose_name_plural': 'Витрина топ-товаров на главной',
            },
        ),
    ]
