# Generated by Django 6.0.6 on 2026-06-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_category_icon_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredproductssettings',
            name='cart_button_text',
            field=models.CharField(default='+ Add to Cart', max_length=50, verbose_name='Текст кнопки добавления в корзину'),
        ),
    ]
