# Generated by Django 6.0.6 on 2026-06-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_featuredproductssettings_cart_button_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_url', models.URLField(blank=True, help_text='Оставьте пустым, чтобы убрать значок', max_length=300, null=True, verbose_name='Ссылка на Instagram')),
                ('telegram_url', models.URLField(blank=True, help_text='Оставьте пустым, чтобы убрать значок', max_length=300, null=True, verbose_name='Ссылка на Telegram')),
                ('copyright_text', models.CharField(default='© 2026 KÓTI. Все права защищены.', max_length=100, verbose_name='Текст копирайта в самом низу')),
            ],
            options={
                'verbose_name': 'Настройки подвала (Футера)',
                'verbose_name_plural': 'Настройки подвала (Футера)',
            },
        ),
    ]
