# Generated by Django 6.0.6 on 2026-06-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_footersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbanner',
            name='banner_size',
            field=models.CharField(choices=[('small', 'Компактный (высота 240px)'), ('medium', 'Стандартный (высота 310px)'), ('large', 'Большой (высота 400px)')], default='small', max_length=10, verbose_name='Размер баннера по высоте'),
        ),
    ]
