# Generated by Django 6.0.6 on 2026-06-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_mainbanner_banner_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryblocksettings',
            name='block_size',
            field=models.CharField(choices=[('small', 'Маленькие плашки (100px)'), ('medium', 'Средние плашки (120px)'), ('large', 'Большие плашки (150px)')], default='medium', max_length=10, verbose_name='Размер круглых категорий'),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='banner_size',
            field=models.CharField(choices=[('small', 'Компактный (высота 200px)'), ('medium', 'Стандартный (высота 280px)'), ('large', 'Высокий (высота 360px)')], default='medium', max_length=10, verbose_name='Высота промо-баннера'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Ссылка на Instagram'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='telegram_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Ссылка на Telegram'),
        ),
    ]
