# Generated by Django 6.0.6 on 2026-06-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_categoryblocksettings_block_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryblocksettings',
            name='block_padding',
            field=models.CharField(choices=[('small', 'Компактные поля (внутренний отступ 20px)'), ('medium', 'Стандартные поля (внутренний отступ 40px)'), ('large', 'Просторные поля (внутренний отступ 60px)')], default='medium', max_length=10, verbose_name='Внутренние отступы белого поля'),
        ),
    ]
