# Generated by Django 6.0.6 on 2026-06-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_categoryblocksettings_block_padding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название цвета')),
                ('code', models.CharField(blank=True, help_text='Например, #HEX или просто текст', max_length=7, verbose_name='Код цвета (опционально)')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Фильтр: Цвета',
            },
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назначение (комната)')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug (для URL)')),
            ],
            options={
                'verbose_name': 'Назначение',
                'verbose_name_plural': 'Фильтр: Назначения',
            },
        ),
        migrations.AlterField(
            model_name='categoryblocksettings',
            name='browse_all_link',
            field=models.CharField(default='/catalog/', max_length=200, verbose_name="Ссылка 'Смотреть все'"),
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.color', verbose_name='Цвета товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='purposes',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.purpose', verbose_name='Назначение'),
        ),
    ]
