# Generated by Django 6.0.6 on 2026-06-17 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_color_purpose_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('pickup', 'Самовывоз'), ('courier', 'Курьер')], max_length=10, unique=True, verbose_name='Тип доставки')),
                ('title', models.CharField(max_length=100, verbose_name='Название способа')),
                ('timeline', models.CharField(help_text='Например: Завтра, 12 ноября', max_length=100, verbose_name='Сроки доставки (строка)')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Стоимость доставки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Способ получения',
                'verbose_name_plural': 'Способы получения',
            },
        ),
        migrations.CreateModel(
            name='OrderFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Подпись поля / Плейсхолдер')),
                ('field_name', models.CharField(max_length=50, unique=True, verbose_name='Имя поля в БД (английскими буквами, например: floor)')),
                ('field_type', models.CharField(choices=[('text', 'Текстовая строка (ФИО, Адрес)'), ('tel', 'Телефон'), ('email', 'Email'), ('textarea', 'Многострочное текстовое поле')], default='text', max_length=15, verbose_name='Тип поля ввода')),
                ('section', models.CharField(choices=[('address', 'Блок «Адрес»'), ('recipient', 'Блок «Данные получателя»')], default='recipient', max_length=15, verbose_name='Раздел формы')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательное поле')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Поле формы заказа',
                'verbose_name_plural': 'Поля формы заказа',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Идентификатор (латиница)')),
                ('title', models.CharField(max_length=100, verbose_name='Название метода оплаты')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='categoryblocksettings',
            options={'verbose_name': 'Настройки блока категорий', 'verbose_name_plural': 'Настройки блоков категорий'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
        migrations.AlterModelOptions(
            name='featuredproductssettings',
            options={'verbose_name': 'Настройки Топа продаж', 'verbose_name_plural': 'Настройки Топа продаж'},
        ),
        migrations.AlterModelOptions(
            name='footersettings',
            options={'verbose_name': 'Настройки подвала', 'verbose_name_plural': 'Настройки подвала'},
        ),
        migrations.AlterModelOptions(
            name='headernavigation',
            options={'verbose_name': 'Ссылка меню', 'verbose_name_plural': 'Ссылки меню'},
        ),
        migrations.AlterModelOptions(
            name='mainbanner',
            options={'verbose_name': 'Главный баннер', 'verbose_name_plural': 'Главные баннеры'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='promobanner',
            options={'verbose_name': 'Промо-баннер', 'verbose_name_plural': 'Промо-баннеры'},
        ),
        migrations.AlterModelOptions(
            name='purpose',
            options={'verbose_name': 'Назначение', 'verbose_name_plural': 'Назначения'},
        ),
        migrations.RemoveField(
            model_name='color',
            name='code',
        ),
        migrations.RemoveField(
            model_name='headernavigation',
            name='order',
        ),
        migrations.RemoveField(
            model_name='headersettings',
            name='promo_text',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created',
        ),
        migrations.RemoveField(
            model_name='purpose',
            name='slug',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(default='Не указан', max_length=50, verbose_name='Способ получения'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Стоимость доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='form_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Заполненные поля формы'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Не указан', max_length=100, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/icons/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_position',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='categoryblocksettings',
            name='block_padding',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='categoryblocksettings',
            name='block_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='categoryblocksettings',
            name='block_title',
            field=models.CharField(default='Shop by Category', max_length=200),
        ),
        migrations.AlterField(
            model_name='categoryblocksettings',
            name='browse_all_link',
            field=models.CharField(default='/catalog/', max_length=200),
        ),
        migrations.AlterField(
            model_name='categoryblocksettings',
            name='browse_all_text',
            field=models.CharField(default='Browse all →', max_length=50),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='featuredproductssettings',
            name='block_title',
            field=models.CharField(default='Топ продаж', max_length=200),
        ),
        migrations.AlterField(
            model_name='featuredproductssettings',
            name='cart_button_text',
            field=models.CharField(default='+ Add to Cart', max_length=50),
        ),
        migrations.AlterField(
            model_name='featuredproductssettings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='featuredproductssettings',
            name='products',
            field=models.ManyToManyField(blank=True, to='shop.product'),
        ),
        migrations.AlterField(
            model_name='featuredproductssettings',
            name='view_all_link',
            field=models.CharField(default='/catalog/', max_length=200),
        ),
        migrations.AlterField(
            model_name='featuredproductssettings',
            name='view_all_text',
            field=models.CharField(default='View all →', max_length=50),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='copyright_text',
            field=models.CharField(default='© 2026 KÓTI. Все права защищены.', max_length=200),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='telegram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='headernavigation',
            name='link',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='headernavigation',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='logo_icon',
            field=models.CharField(default='★', max_length=10),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='site_name',
            field=models.CharField(default='KÓTI', max_length=100),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='banner_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='button_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='button_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='payment_subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='payment_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='shipping_subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='shipping_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='show_payment_badge',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='show_shipping_badge',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='sub_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='items_summary',
            field=models.TextField(verbose_name='Состав заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая сумма'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, to='shop.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_position',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='purposes',
            field=models.ManyToManyField(blank=True, to='shop.purpose'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='badge_bottom_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='badge_up_to_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='badge_value_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='banner_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='button_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='button_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='promo/'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='tag_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
