# Generated by Django 6.0.6 on 2026-06-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_deliverymethod_orderformfield_paymentmethod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], unique=True, verbose_name='День недели')),
                ('is_working', models.BooleanField(default=True, verbose_name='Рабочий день')),
                ('work_from', models.TimeField(default='09:00', verbose_name='Работаем с')),
                ('work_to', models.TimeField(default='21:00', verbose_name='Работаем до')),
                ('courier_cutoff_time', models.TimeField(default='15:00', help_text='Если клиент заказывает позже этого времени, доставка переносится на следующий рабочий день.', verbose_name='Время отсечки для доставки день в день')),
            ],
            options={
                'verbose_name': 'График работы дня',
                'verbose_name_plural': 'График работы (Дни недели)',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.RemoveField(
            model_name='deliverymethod',
            name='timeline',
        ),
        migrations.AlterField(
            model_name='deliverymethod',
            name='method_type',
            field=models.CharField(choices=[('pickup', 'pickup'), ('courier', 'courier')], max_length=10, unique=True, verbose_name='Тип доставки'),
        ),
    ]
