# Generated by Django 6.0.6 on 2026-06-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_workingschedule_remove_deliverymethod_timeline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='related_to', to='shop.product', verbose_name='Похожие / Сопутствующие товары'),
        ),
    ]
