# Generated by Django 6.0.6 on 2026-06-18 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_product_related_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО Курьера / Название службы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен (выезжает на заказы)')),
            ],
            options={
                'verbose_name': 'Курьер',
                'verbose_name_plural': 'Курьеры',
            },
        ),
        migrations.AlterModelOptions(
            name='workingschedule',
            options={'ordering': ['day_of_week'], 'verbose_name': 'График работы магазина', 'verbose_name_plural': 'График магазина (Самовывоз)'},
        ),
        migrations.RemoveField(
            model_name='workingschedule',
            name='courier_cutoff_time',
        ),
        migrations.AlterField(
            model_name='workingschedule',
            name='is_working',
            field=models.BooleanField(default=True, verbose_name='Рабочий день магазина'),
        ),
        migrations.CreateModel(
            name='CourierSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('is_working', models.BooleanField(default=True, verbose_name='Рабочий день курьера')),
                ('work_from', models.TimeField(default='10:00', verbose_name='Рабочая смена с')),
                ('work_to', models.TimeField(default='20:00', verbose_name='Рабочая смена до')),
                ('courier_cutoff_time', models.TimeField(default='15:00', help_text='Если клиент заказывает позже этого времени, этот курьер сегодня заказ уже не возьмет.', verbose_name='Время отсечки для доставки день в день')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='shop.courier', verbose_name='Курьер')),
            ],
            options={
                'verbose_name': 'Рабочий день курьера',
                'verbose_name_plural': 'Графики работы курьеров',
                'ordering': ['courier', 'day_of_week'],
                'unique_together': {('courier', 'day_of_week')},
            },
        ),
    ]
