# Generated by Django 6.0.6 on 2026-06-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_courier_alter_workingschedule_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='price_updates/', verbose_name='Файл прайс-листа (CSV)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('log', models.TextField(blank=True, verbose_name='Отчет об обновлении')),
            ],
            options={
                'verbose_name': 'Обновление цен',
                'verbose_name_plural': 'Обновления цен (Загрузка прайса)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Артикул'),
        ),
    ]
