# Generated by Django 6.0.6 on 2026-06-19 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_priceupdate_product_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryblocksettings',
            options={'verbose_name': 'Настройки блока категорий', 'verbose_name_plural': 'Настройки блока категорий'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Цвет', 'verbose_name_plural': 'Справочник: Цвета'},
        ),
        migrations.AlterModelOptions(
            name='courier',
            options={'verbose_name': 'Курьер', 'verbose_name_plural': 'Логистика: Курьеры'},
        ),
        migrations.AlterModelOptions(
            name='courierschedule',
            options={'ordering': ['courier', 'day_of_week'], 'verbose_name': 'Смена курьера', 'verbose_name_plural': 'Смены курьеров'},
        ),
        migrations.AlterModelOptions(
            name='deliverymethod',
            options={'verbose_name': 'Способ получения', 'verbose_name_plural': 'Логистика: Способы получения'},
        ),
        migrations.AlterModelOptions(
            name='footersettings',
            options={'verbose_name': 'Настройки подвала (соцсети)', 'verbose_name_plural': 'Настройки подвала (соцсети)'},
        ),
        migrations.AlterModelOptions(
            name='headernavigation',
            options={'verbose_name': 'Ссылка главного меню', 'verbose_name_plural': 'Ссылки главного меню'},
        ),
        migrations.AlterModelOptions(
            name='headersettings',
            options={'verbose_name': 'Настройки шапки (Лого)', 'verbose_name_plural': 'Настройки шапки (Лого)'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы клиентов'},
        ),
        migrations.AlterModelOptions(
            name='orderformfield',
            options={'ordering': ['sort_order'], 'verbose_name': 'Поле формы заказа', 'verbose_name_plural': 'Справочник: Поля формы заказа'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'Способ оплаты', 'verbose_name_plural': 'Логистика: Способы оплаты'},
        ),
        migrations.AlterModelOptions(
            name='priceupdate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Обновление цен (Прайс-лист)', 'verbose_name_plural': 'Обновления цен (Прайс-листы)'},
        ),
        migrations.AlterModelOptions(
            name='promobanner',
            options={'verbose_name': 'Промо-баннер (Акция)', 'verbose_name_plural': 'Промо-баннеры (Акции)'},
        ),
        migrations.AlterModelOptions(
            name='purpose',
            options={'verbose_name': 'Назначение', 'verbose_name_plural': 'Справочник: Назначения'},
        ),
        migrations.AlterModelOptions(
            name='workingschedule',
            options={'ordering': ['day_of_week'], 'verbose_name': 'График работы шоурума', 'verbose_name_plural': 'Логистика: График работы шоурума'},
        ),
        migrations.RemoveField(
            model_name='priceupdate',
            name='csv_file',
        ),
        migrations.AddField(
            model_name='priceupdate',
            name='excel_file',
            field=models.FileField(default='', help_text='Загрузите файл Excel (.xlsx). Колонка А = Артикул, Колонка B = Новая цена.', upload_to='price_updates/', verbose_name='Файл прайс-листа (.xlsx)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Маленькая квадратная/круглая картинка для меню.', null=True, upload_to='categories/icons/', verbose_name='Иконка категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_position',
            field=models.IntegerField(default=50, help_text='50 - центр, 0 - верх, 100 - низ. Помогает сдвинуть фокус на фото.', verbose_name='Центровка иконки (%)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Большая картинка для прямоугольных плиток категорий.', null=True, upload_to='categories/', verbose_name='Фото категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Поставьте галочку, чтобы эта категория появилась в блоке на главной странице.', verbose_name='Выводить на главную?'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, help_text="Например: 'Кухня' или 'Ванная'. Клиенты увидят это в меню.", max_length=200, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Оставьте пустым, заполнится само латинскими буквами (например: kuhnya).', max_length=200, unique=True, verbose_name='URL-адрес (ссылка)'),
        ),
        migrations.AlterField(
            model_name='categoryblocksettings',
            name='block_padding',
            field=models.CharField(choices=[('small', 'Маленькие'), ('medium', 'Средние'), ('large', 'Большие')], default='medium', max_length=20, verbose_name='Отступы блока'),
        ),
        migrations.AlterField(
            model_name='categoryblocksettings',
            name='block_size',
            field=models.CharField(choices=[('small', 'Мелкие'), ('medium', 'Средние'), ('large', 'Крупные')], default='medium', max_length=20, verbose_name='Размер кружков'),
        ),
        migrations.AlterField(
            model_name='categoryblocksettings',
            name='block_title',
            field=models.CharField(default='Shop by Category', help_text="Текст над круглыми категориями на главной (например: 'Популярные разделы').", max_length=200, verbose_name='Заголовок блока'),
        ),
        migrations.AlterField(
            model_name='categoryblocksettings',
            name='browse_all_link',
            field=models.CharField(default='/catalog/', max_length=200, verbose_name='Ссылка "Смотреть все"'),
        ),
        migrations.AlterField(
            model_name='categoryblocksettings',
            name='browse_all_text',
            field=models.CharField(default='Browse all →', max_length=50, verbose_name='Текст ссылки "Смотреть все"'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(help_text="Например: 'Бежевый', 'Прозрачный'. Поможет клиентам фильтровать товары.", max_length=100, verbose_name='Название цвета'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Снимите галочку, если курьер в отпуске/уволен.', verbose_name='Активен (работает)'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='name',
            field=models.CharField(help_text="Например: 'Александр' или 'Яндекс.Доставка'.", max_length=100, verbose_name='Имя курьера / Служба'),
        ),
        migrations.AlterField(
            model_name='courierschedule',
            name='courier_cutoff_time',
            field=models.TimeField(default='15:00', help_text='Если клиент сделает заказ ПОЗЖЕ этого времени, система скажет ему, что доставка будет только на следующий рабочий день.', verbose_name='Время отсечки (дедлайн)'),
        ),
        migrations.AlterField(
            model_name='courierschedule',
            name='is_working',
            field=models.BooleanField(default=True, verbose_name='Рабочий день'),
        ),
        migrations.AlterField(
            model_name='courierschedule',
            name='work_from',
            field=models.TimeField(default='10:00', verbose_name='Начало смены'),
        ),
        migrations.AlterField(
            model_name='courierschedule',
            name='work_to',
            field=models.TimeField(default='20:00', verbose_name='Конец смены'),
        ),
        migrations.AlterField(
            model_name='deliverymethod',
            name='method_type',
            field=models.CharField(choices=[('pickup', 'Самовывоз (из магазина)'), ('courier', 'Доставка (курьер/почта)')], help_text='Система будет брать даты либо из графика шоурума (pickup), либо из графика курьеров (courier).', max_length=10, unique=True, verbose_name='Тип расчета дат'),
        ),
        migrations.AlterField(
            model_name='deliverymethod',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Оставьте 0 для бесплатной доставки.', max_digits=10, verbose_name='Стоимость (руб.)'),
        ),
        migrations.AlterField(
            model_name='deliverymethod',
            name='title',
            field=models.CharField(help_text="Например: 'Курьером до двери'.", max_length=100, verbose_name='Название способа'),
        ),
        migrations.AlterField(
            model_name='featuredproductssettings',
            name='block_title',
            field=models.CharField(default='Топ продаж', help_text="Например: 'Хиты этой недели'.", max_length=200, verbose_name='Заголовок блока'),
        ),
        migrations.AlterField(
            model_name='featuredproductssettings',
            name='cart_button_text',
            field=models.CharField(default='В корзину', max_length=50, verbose_name='Текст кнопки корзины'),
        ),
        migrations.AlterField(
            model_name='featuredproductssettings',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показывать блок на сайте?'),
        ),
        migrations.AlterField(
            model_name='featuredproductssettings',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Выберите ровно 5 товаров для идеальной сетки.', to='shop.product', verbose_name='Товары для вывода'),
        ),
        migrations.AlterField(
            model_name='featuredproductssettings',
            name='view_all_link',
            field=models.CharField(default='/catalog/', max_length=200, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='featuredproductssettings',
            name='view_all_text',
            field=models.CharField(default='Смотреть все →', max_length=50, verbose_name='Текст ссылки'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='copyright_text',
            field=models.CharField(default='© 2026 KÓTI. Все права защищены.', max_length=200, verbose_name='Текст копирайта'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Если оставить пустым, иконка Инстаграм скроется.', null=True, verbose_name='Ссылка на Instagram'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='telegram_url',
            field=models.URLField(blank=True, help_text='Если оставить пустым, иконка Телеграм скроется.', null=True, verbose_name='Ссылка на Telegram'),
        ),
        migrations.AlterField(
            model_name='headernavigation',
            name='link',
            field=models.CharField(help_text="Укажите URL (например: '/about/').", max_length=200, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='headernavigation',
            name='title',
            field=models.CharField(help_text="Например: 'О нас' или 'Доставка'.", max_length=100, verbose_name='Название пункта меню'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='logo_icon',
            field=models.CharField(default='♥', help_text='Иконка или эмодзи рядом с названием (например: ♥, ★, ⌂).', max_length=10, verbose_name='Символ логотипа'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='site_name',
            field=models.CharField(default='KÓTI', help_text='Название, которое выводится в левом верхнем углу.', max_length=100, verbose_name='Название сайта (Логотип)'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='banner_size',
            field=models.CharField(choices=[('small', 'Узкий'), ('medium', 'Средний'), ('large', 'Широкий (на весь экран)')], default='medium', help_text='Определяет высоту картинки на сайте.', max_length=20, verbose_name='Размер баннера'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='button_link',
            field=models.CharField(blank=True, help_text="Куда перейдет клиент (например: '/catalog/' или полная ссылка 'https://...').", max_length=200, verbose_name='Ссылка с кнопки'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='button_text',
            field=models.CharField(blank=True, help_text="Например: 'Смотреть новинки'. Если оставить пустым, кнопка скроется.", max_length=50, verbose_name='Текст на кнопке'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='description',
            field=models.TextField(blank=True, help_text='Поясняющий текст под главным заголовком.', verbose_name='Подзаголовок (описание)'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='image',
            field=models.ImageField(blank=True, help_text='Красивое фото для фона. Текст будет наложен поверх него.', null=True, upload_to='banners/', verbose_name='Фоновое изображение'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Снимите галочку, чтобы убрать баннер с сайта.', verbose_name='Включить баннер'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='payment_subtitle',
            field=models.CharField(blank=True, help_text="Например: 'Картой онлайн или при получении'", max_length=100, verbose_name='Подтекст оплаты'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='payment_title',
            field=models.CharField(blank=True, help_text="Например: 'Безопасная оплата'", max_length=100, verbose_name='Заголовок оплаты'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='shipping_subtitle',
            field=models.CharField(blank=True, help_text="Например: 'Европочтой или курьером'", max_length=100, verbose_name='Подтекст доставки'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='shipping_title',
            field=models.CharField(blank=True, help_text="Например: 'Доставка по РБ'", max_length=100, verbose_name='Заголовок доставки'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='show_payment_badge',
            field=models.BooleanField(default=True, verbose_name='Показывать плашку оплаты?'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='show_shipping_badge',
            field=models.BooleanField(default=True, verbose_name='Показывать плашку доставки?'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='sub_title',
            field=models.CharField(blank=True, help_text="Мелкий текст над главным названием (например: 'НОВАЯ КОЛЛЕКЦИЯ').", max_length=100, verbose_name='Надзаголовок'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='title',
            field=models.CharField(help_text="Крупный текст баннера (например: 'Осенний уют в каждый дом').", max_length=200, verbose_name='Главный заголовок'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(default='Не указан', max_length=150, verbose_name='Способ получения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='form_data',
            field=models.JSONField(blank=True, default=dict, help_text='Здесь хранятся все введенные клиентом адреса и телефоны.', verbose_name='Заполненные данные клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items_summary',
            field=models.TextField(verbose_name='Состав заказа (Товары)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая сумма (с доставкой)'),
        ),
        migrations.AlterField(
            model_name='orderformfield',
            name='field_name',
            field=models.CharField(help_text='Только латиницей без пробелов (например: phone, street, apartment).', max_length=50, unique=True, verbose_name='Системное имя'),
        ),
        migrations.AlterField(
            model_name='orderformfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Текстовая строка'), ('tel', 'Телефон'), ('email', 'Email'), ('textarea', 'Многострочный текст')], default='text', help_text='Как это поле будет выглядеть.', max_length=15, verbose_name='Тип поля'),
        ),
        migrations.AlterField(
            model_name='orderformfield',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Клиент не сможет оформить заказ, пока не заполнит это поле.', verbose_name='Обязательное?'),
        ),
        migrations.AlterField(
            model_name='orderformfield',
            name='label',
            field=models.CharField(help_text="Например: 'Ваш телефон' или 'Квартира'.", max_length=100, verbose_name='Название поля (подсказка)'),
        ),
        migrations.AlterField(
            model_name='orderformfield',
            name='section',
            field=models.CharField(choices=[('address', 'Блок «Адрес»'), ('recipient', 'Блок «Данные получателя»')], default='recipient', max_length=15, verbose_name='В каком блоке показывать?'),
        ),
        migrations.AlterField(
            model_name='orderformfield',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Чем меньше цифра, тем выше поле в форме (например: 1, 2, 3).', verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='slug',
            field=models.SlugField(help_text='Напишите латиницей без пробелов (например: cash, card_online).', unique=True, verbose_name='Системный код'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='title',
            field=models.CharField(help_text="Например: 'Картой при получении'.", max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='priceupdate',
            name='log',
            field=models.TextField(blank=True, help_text='Здесь появится информация о том, какие товары обновились.', verbose_name='Отчет системы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, help_text='Снимите галочку, если товар закончился. Он скроется из каталога на сайте.', verbose_name='В наличии (Активен)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Выберите раздел, в котором будет лежать этот товар.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, help_text='Выберите цвета, присутствующие в товаре.', to='shop.color', verbose_name='Цвета (для фильтров)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Подробное описание товара, материалы, размеры и уход. Можно использовать переносы строк.', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Главная фотография товара в высоком разрешении. Желательно квадратная (1:1).', upload_to='products/%Y/%m/%d', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_position',
            field=models.IntegerField(default=50, help_text='От 0 до 100. Если фото обрезается некрасиво, поменяйте значение, чтобы сдвинуть фокус.', verbose_name='Центровка фото (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, help_text="Полное наименование (например: 'Набор стеклянных баночек с бамбуковой крышкой').", max_length=200, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Стоимость в белорусских рублях (вводите через точку, например: 45.00).', max_digits=10, verbose_name='Цена (руб.)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purposes',
            field=models.ManyToManyField(blank=True, help_text='Выберите одно или несколько (зажмите Ctrl/Cmd для мультивыбора).', to='shop.purpose', verbose_name='Назначения (для фильтров)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, help_text="Выберите товары, которые клиент увидит в блоке 'Вам также может понравиться' внизу карточки.", related_name='related_to', to='shop.product', verbose_name='Похожие товары'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, help_text='Уникальный код товара (например: KOTI-001). По нему можно массово обновлять цены из Excel.', max_length=50, null=True, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='Генерируется автоматически из названия.', max_length=200, verbose_name='URL-адрес'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='badge_bottom_text',
            field=models.CharField(blank=True, help_text="Например: 'на всё'", max_length=50, verbose_name='Нижний текст кружка'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='badge_up_to_text',
            field=models.CharField(blank=True, help_text="Например: 'До'", max_length=50, verbose_name='Верхний текст кружка'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='badge_value_text',
            field=models.CharField(blank=True, help_text="Например: '-20%'", max_length=50, verbose_name='Главная цифра кружка'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='banner_size',
            field=models.CharField(choices=[('small', 'Узкий'), ('medium', 'Средний'), ('large', 'Крупный')], default='medium', max_length=20, verbose_name='Размер баннера'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='button_link',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ссылка кнопки'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='promo/', verbose_name='Фото баннера'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Включен'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='tag_text',
            field=models.CharField(blank=True, help_text="Например: 'РАСПРОДАЖА'", max_length=100, verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='title',
            field=models.CharField(help_text="Например: 'Скидки на текстиль'", max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='name',
            field=models.CharField(help_text="Например: 'Для хранения', 'Для сервировки'. Используется в фильтрах каталога.", max_length=100, verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='workingschedule',
            name='is_working',
            field=models.BooleanField(default=True, help_text='Снимите галочку, если магазин (шоурум) закрыт в этот день.', verbose_name='Рабочий день?'),
        ),
        migrations.AlterField(
            model_name='workingschedule',
            name='work_from',
            field=models.TimeField(default='09:00', help_text='Формат ЧЧ:ММ', verbose_name='Открыто с'),
        ),
        migrations.AlterField(
            model_name='workingschedule',
            name='work_to',
            field=models.TimeField(default='21:00', help_text='Формат ЧЧ:ММ', verbose_name='Открыто до'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/%Y/%m/%d', verbose_name='Дополнительное фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Дополнительное фото',
                'verbose_name_plural': 'Галерея товара',
            },
        ),
    ]
