# Generated by Django 6.0.6 on 2026-06-19 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_categoryblocksettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Оставьте пустым, заполнится само латинскими буквами.', max_length=200, unique=True, verbose_name='URL-адрес (ссылка)'),
        ),
        migrations.AlterField(
            model_name='categoryblocksettings',
            name='block_title',
            field=models.CharField(default='Shop by Category', max_length=200, verbose_name='Заголовок блока'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(help_text="Например: 'Бежевый', 'Прозрачный'.", max_length=100, verbose_name='Название цвета'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен (работает)'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя курьера / Служба'),
        ),
        migrations.AlterField(
            model_name='courierschedule',
            name='courier_cutoff_time',
            field=models.TimeField(default='15:00', verbose_name='Время отсечки (дедлайн)'),
        ),
        migrations.AlterField(
            model_name='deliverymethod',
            name='method_type',
            field=models.CharField(choices=[('pickup', 'Самовывоз (из магазина)'), ('courier', 'Доставка (курьер/почта)')], max_length=10, unique=True, verbose_name='Тип расчета дат'),
        ),
        migrations.AlterField(
            model_name='deliverymethod',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Стоимость (руб.)'),
        ),
        migrations.AlterField(
            model_name='deliverymethod',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название способа'),
        ),
        migrations.AlterField(
            model_name='featuredproductssettings',
            name='block_title',
            field=models.CharField(default='Топ продаж', max_length=200, verbose_name='Заголовок блока'),
        ),
        migrations.AlterField(
            model_name='featuredproductssettings',
            name='products',
            field=models.ManyToManyField(blank=True, to='shop.product', verbose_name='Товары для вывода'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Instagram'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='telegram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Telegram'),
        ),
        migrations.AlterField(
            model_name='headernavigation',
            name='link',
            field=models.CharField(max_length=200, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='headernavigation',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название пункта меню'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='logo_icon',
            field=models.CharField(default='♥', max_length=10, verbose_name='Символ логотипа'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='site_name',
            field=models.CharField(default='KÓTI', max_length=100, verbose_name='Название сайта (Логотип)'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='banner_size',
            field=models.CharField(choices=[('small', 'Узкий'), ('medium', 'Средний'), ('large', 'Широкий')], default='medium', max_length=20, verbose_name='Размер баннера'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='button_link',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ссылка с кнопки'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='Текст на кнопке'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='description',
            field=models.TextField(blank=True, verbose_name='Подзаголовок (описание)'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Фоновое изображение'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Включить баннер'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='payment_subtitle',
            field=models.CharField(blank=True, max_length=100, verbose_name='Подтекст оплаты'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='payment_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Заголовок оплаты'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='shipping_subtitle',
            field=models.CharField(blank=True, max_length=100, verbose_name='Подтекст доставки'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='shipping_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Заголовок доставки'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='sub_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Надзаголовок'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Главный заголовок'),
        ),
        migrations.AlterField(
            model_name='order',
            name='form_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Заполненные данные клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items_summary',
            field=models.TextField(verbose_name='Состав заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая сумма'),
        ),
        migrations.AlterField(
            model_name='orderformfield',
            name='field_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Системное имя'),
        ),
        migrations.AlterField(
            model_name='orderformfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Текстовая строка'), ('tel', 'Телефон'), ('email', 'Email'), ('textarea', 'Многострочный текст')], default='text', max_length=15, verbose_name='Тип поля'),
        ),
        migrations.AlterField(
            model_name='orderformfield',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='Обязательное?'),
        ),
        migrations.AlterField(
            model_name='orderformfield',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Название поля (подсказка)'),
        ),
        migrations.AlterField(
            model_name='orderformfield',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Системный код'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='priceupdate',
            name='log',
            field=models.TextField(blank=True, verbose_name='Отчет системы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='В наличии (Активен)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, to='shop.color', verbose_name='Цвета (для фильтров)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Подробное описание товара, материалы, размеры.', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_position',
            field=models.IntegerField(default=50, verbose_name='Центровка фото (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (руб.)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purposes',
            field=models.ManyToManyField(blank=True, to='shop.purpose', verbose_name='Назначения (для фильтров)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='related_to', to='shop.product', verbose_name='Похожие товары'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, help_text='Уникальный код товара (например: KOTI-001). Нужен для автообновления цен из Excel.', max_length=50, null=True, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=200, verbose_name='URL-адрес'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='badge_bottom_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='Нижний текст кружка'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='badge_up_to_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='Верхний текст кружка'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='badge_value_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='Главная цифра кружка'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='tag_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='name',
            field=models.CharField(help_text="Например: 'Для хранения', 'Для сервировки'.", max_length=100, verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='workingschedule',
            name='is_working',
            field=models.BooleanField(default=True, verbose_name='Рабочий день?'),
        ),
        migrations.AlterField(
            model_name='workingschedule',
            name='work_from',
            field=models.TimeField(default='09:00', verbose_name='Открыто с'),
        ),
        migrations.AlterField(
            model_name='workingschedule',
            name='work_to',
            field=models.TimeField(default='21:00', verbose_name='Открыто до'),
        ),
    ]
