# Generated by Django 6.0.6 on 2026-06-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_position',
            field=models.IntegerField(default=50, help_text='От 0 до 100. Настройка фокуса для этого фото.', verbose_name='Центровка фото (%)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Поставьте галочку, чтобы эта категория появилась в锁локе на главной странице.', verbose_name='Выводить на главную?'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(help_text="Например: 'Бежевый', 'Прозрачный'. Поможет клиентам фильтровать товары.", max_length=100, verbose_name='Название цвета'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_position',
            field=models.IntegerField(default=50, help_text='От 0 до 100. Помогает настроить фокус основного изображения.', verbose_name='Центровка фото (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, help_text='Уникальный код товара (например: KOTI-001). По нему можно массово обновлять цены из Excel.', max_length=50, null=True, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='name',
            field=models.CharField(help_text="Например: 'Для хранения', 'Для сервировки'. Используется в фильтрах каталога.", max_length=100, verbose_name='Назначение'),
        ),
    ]
