# Generated by Django 6.0.6 on 2026-06-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_productimage_image_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryblocksettings',
            options={'verbose_name': 'Блок категорий', 'verbose_name_plural': 'Настройки блока категорий'},
        ),
        migrations.AlterModelOptions(
            name='featuredproductssettings',
            options={'verbose_name': 'Топ продаж', 'verbose_name_plural': 'Настройки Топа продаж'},
        ),
        migrations.AlterModelOptions(
            name='footersettings',
            options={'verbose_name': 'Настройки подвала', 'verbose_name_plural': 'Настройки подвала (соцсети)'},
        ),
        migrations.AlterModelOptions(
            name='priceupdate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Обновление цен и остатков', 'verbose_name_plural': 'Обновления из Excel'},
        ),
        migrations.AlterModelOptions(
            name='workingschedule',
            options={'ordering': ['day_of_week'], 'verbose_name': 'График шоурума', 'verbose_name_plural': 'Логистика: График работы шоурума'},
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Сколько штук доступно для заказа.', verbose_name='Остаток на складе'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Поставьте галочку, чтобы эта категория появилась в блоке на главной странице.', verbose_name='Выводить на главную?'),
        ),
        migrations.AlterField(
            model_name='categoryblocksettings',
            name='browse_all_link',
            field=models.CharField(default='/catalog/', max_length=200, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='categoryblocksettings',
            name='browse_all_text',
            field=models.CharField(default='Browse all →', max_length=50, verbose_name='Текст ссылки'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='courierschedule',
            name='courier_cutoff_time',
            field=models.TimeField(default='15:00', verbose_name='Время отсечки'),
        ),
        migrations.AlterField(
            model_name='deliverymethod',
            name='method_type',
            field=models.CharField(choices=[('pickup', 'Самовывоз'), ('courier', 'Доставка')], max_length=10, unique=True, verbose_name='Тип расчета дат'),
        ),
        migrations.AlterField(
            model_name='featuredproductssettings',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показывать блок?'),
        ),
        migrations.AlterField(
            model_name='featuredproductssettings',
            name='products',
            field=models.ManyToManyField(blank=True, to='shop.product', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='copyright_text',
            field=models.CharField(default='© 2026 KÓTI.', max_length=200, verbose_name='Копирайт'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='telegram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='headernavigation',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Пункт меню'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='site_name',
            field=models.CharField(default='KÓTI', max_length=100, verbose_name='Название сайта'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='banner_size',
            field=models.CharField(choices=[('small', 'Узкий'), ('medium', 'Средний'), ('large', 'Широкий')], default='medium', max_length=20, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Фон'),
        ),
        migrations.AlterField(
            model_name='orderformfield',
            name='section',
            field=models.CharField(choices=[('address', 'Блок «Адрес»'), ('recipient', 'Блок «Данные получателя»')], default='recipient', max_length=15, verbose_name='Блок'),
        ),
        migrations.AlterField(
            model_name='orderformfield',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='priceupdate',
            name='excel_file',
            field=models.FileField(help_text='Колонка А = Артикул, Колонка B = Цена, Колонка C = Остаток.', upload_to='price_updates/', verbose_name='Файл прайс-листа (.xlsx)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, to='shop.color', verbose_name='Цвета'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_position',
            field=models.IntegerField(default=50, verbose_name='Центровка фото (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purposes',
            field=models.ManyToManyField(blank=True, to='shop.purpose', verbose_name='Назначения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, help_text='Уникальный код (например: KOTI-001). По нему обновляются цены из Excel.', max_length=50, null=True, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_position',
            field=models.IntegerField(default=50, verbose_name='Центровка фото (%)'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='badge_value_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='Цифра кружка'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='banner_size',
            field=models.CharField(choices=[('small', 'Узкий'), ('medium', 'Средний'), ('large', 'Крупный')], default='medium', max_length=20, verbose_name='Размер'),
        ),
    ]
