# Generated by Django 6.0.6 on 2026-06-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_alter_categoryblocksettings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headersettings',
            options={'verbose_name': 'Настройки шапки (Лого и Email)', 'verbose_name_plural': 'Настройки шапки (Лого и Email)'},
        ),
        migrations.AddField(
            model_name='headersettings',
            name='admin_email',
            field=models.EmailField(blank=True, help_text='На эту почту будут приходить письма о новых заказах клиентов.', max_length=254, null=True, verbose_name='Email для уведомлений'),
        ),
    ]
