# Generated by Django 6.0.6 on 2026-06-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_alter_headersettings_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReport',
            fields=[
            ],
            options={
                'verbose_name': 'Финансовый отчет',
                'verbose_name_plural': 'Отчет: Выручка и Прибыль',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.order',),
        ),
        migrations.AlterModelOptions(
            name='priceupdate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Обновление прайса (Excel)', 'verbose_name_plural': 'Обновления из Excel'},
        ),
        migrations.AddField(
            model_name='order',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Сумма закупочных цен товаров в этом заказе + доставка поставщика.', max_digits=10, verbose_name='Общая себестоимость'),
        ),
        migrations.AddField(
            model_name='order',
            name='gross_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Выручка с товаров МИНУС их себестоимость.', max_digits=10, verbose_name='Валовая прибыль'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Стоимость закупки 1 единицы товара.', max_digits=10, verbose_name='Закупочная цена (руб.)'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Доля доставки на 1 единицу товара (чтобы прибыль считалась точнее).', max_digits=10, verbose_name='Доставка от поставщика (руб.)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/icons/', verbose_name='Иконка категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_position',
            field=models.IntegerField(default=50, verbose_name='Центровка иконки (%)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Фото категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Выводить на главную?'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='URL-адрес (ссылка)'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название цвета'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='admin_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email для уведомлений'),
        ),
        migrations.AlterField(
            model_name='priceupdate',
            name='excel_file',
            field=models.FileField(help_text='Колонки: A=Артикул, B=Цена продажи, C=Остаток, D=Закупочная цена, E=Доставка поставщика.', upload_to='price_updates/', verbose_name='Файл прайс-листа (.xlsx)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена продажи (руб.)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Остаток на складе'),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назначение'),
        ),
    ]
