# Generated by Django 6.0.6 on 2026-06-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_orderreport_alter_priceupdate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items_purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Закупочная цена товаров'),
        ),
        migrations.AddField(
            model_name='order',
            name='items_retail_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Розничная цена товаров (Выручка)'),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier_shipping_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Доставка от поставщика'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Общая себестоимость'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, default='Не указан', max_length=150, verbose_name='Способ получения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Стоимость нашей доставки клиенту'),
        ),
        migrations.AlterField(
            model_name='order',
            name='form_data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Заполненные данные клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='gross_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Валовая прибыль'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items_summary',
            field=models.TextField(help_text="Например: Свеча 'Ваниль' х 2 шт.", verbose_name='Состав заказа (Список товаров)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, default='Не указан', max_length=100, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Итоговая сумма'),
        ),
        migrations.AlterField(
            model_name='priceupdate',
            name='excel_file',
            field=models.FileField(upload_to='price_updates/', verbose_name='Файл прайс-листа (.xlsx)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Закупочная цена (руб.)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier_shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Доставка от поставщика (руб.)'),
        ),
    ]
