# Generated by Django 6.0.6 on 2026-06-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_order_items_purchase_price_order_items_retail_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='👉 Рассчитывается сама: (Закупочная цена + Доставка от поставщика)', max_digits=10, verbose_name='Общая себестоимость'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Сколько клиент платит нам за курьера или почту.', max_digits=10, verbose_name='Стоимость нашей доставки клиенту'),
        ),
        migrations.AlterField(
            model_name='order',
            name='gross_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='👉 Рассчитывается сама: (Розничная цена товаров МИНУС Общая себестоимость)', max_digits=10, verbose_name='Валовая прибыль (Чистыми)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items_purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Суммарная стоимость закупки этих товаров у поставщика.', max_digits=10, verbose_name='Закупочная цена товаров'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items_retail_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Сколько клиент платит ТОЛЬКО за сами товары (БЕЗ учета доставки).', max_digits=10, verbose_name='Розничная цена товаров (Выручка)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='supplier_shipping_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Сколько вы потратили на логистику этих товаров от поставщика к вам.', max_digits=10, verbose_name='Доставка от поставщика'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='👉 Рассчитывается сама: (Розничная цена товаров + Наша доставка клиенту)', max_digits=10, verbose_name='Итоговая сумма (Чек)'),
        ),
    ]
