# Generated by Django 6.0.6 on 2026-06-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_alter_order_cost_price_alter_order_delivery_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_source',
            field=models.CharField(blank=True, default='Сайт', help_text="Если заказ пришел с сайта, здесь написано 'Сайт'. Для ручных заказов впишите Instagram, Шоурум и т.д.", max_length=100, verbose_name='Откуда заказ'),
        ),
    ]
