# Generated by Django 6.0.6 on 2026-06-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_order_order_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='👉 Рассчитывается сама: (Закупочная цена + Доставка от поставщика)', max_digits=10, null=True, verbose_name='Общая себестоимость'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Сколько клиент платит нам за курьера или почту.', max_digits=10, null=True, verbose_name='Стоимость нашей доставки клиенту'),
        ),
        migrations.AlterField(
            model_name='order',
            name='gross_profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='👉 Рассчитывается сама: (Розничная цена товаров МИНУС Общая себестоимость)', max_digits=10, null=True, verbose_name='Валовая прибыль (Чистыми)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items_purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Суммарная стоимость закупки этих товаров у поставщика.', max_digits=10, null=True, verbose_name='Закупочная цена товаров'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items_retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Сколько клиент платит ТОЛЬКО за сами товары (БЕЗ учета доставки).', max_digits=10, null=True, verbose_name='Розничная цена товаров (Выручка)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_source',
            field=models.CharField(blank=True, help_text="Для ручных заказов впишите: Instagram, Шоурум, Подруга и т.д. Если заказ с сайта, здесь автоматически будет написано 'Сайт'.", max_length=100, null=True, verbose_name='Откуда заказ (Источник)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='supplier_shipping_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Сколько вы потратили на логистику этих товаров от поставщика к вам.', max_digits=10, null=True, verbose_name='Доставка от поставщика'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='👉 Рассчитывается сама: (Розничная цена товаров + Наша доставка клиенту)', max_digits=10, null=True, verbose_name='Итоговая сумма (Чек)'),
        ),
    ]
