# Generated by Django 6.0.6 on 2026-06-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_alter_order_cost_price_alter_order_delivery_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproductssettings',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показывать block?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Сколько клиент платит нам за доставку.', max_digits=10, null=True, verbose_name='Стоимость нашей доставки клиенту'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items_purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Суммарная себестоимость закупки этих товаров.', max_digits=10, null=True, verbose_name='Закупочная цена товаров'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items_retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Стоимость ТОЛЬКО самих товаров (без доставки).', max_digits=10, null=True, verbose_name='Розничная цена товаров (Выручка)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_source',
            field=models.CharField(blank=True, help_text='Для ручных заказов впишите: Instagram, Шоурум, Выставка и т.д. Если заказ с сайта, заполнится автоматически.', max_length=100, null=True, verbose_name='Откуда заказ (Источник)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='supplier_shipping_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Расходы на логистику от поставщика к вам.', max_digits=10, null=True, verbose_name='Доставка от поставщика'),
        ),
    ]
