# Generated by Django 6.0.6 on 2026-06-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_alter_featuredproductssettings_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryblocksettings',
            name='categories',
            field=models.ManyToManyField(blank=True, to='shop.category', verbose_name='Выберите категории для показа на Главной'),
        ),
        migrations.AlterField(
            model_name='categoryblocksettings',
            name='block_title',
            field=models.CharField(default='Категории', max_length=200, verbose_name='Заголовок блока'),
        ),
        migrations.AlterField(
            model_name='categoryblocksettings',
            name='browse_all_text',
            field=models.CharField(default='Все категории →', max_length=50, verbose_name='Текст ссылки'),
        ),
        migrations.AlterField(
            model_name='featuredproductssettings',
            name='cart_button_text',
            field=models.CharField(default='Добавить в корзину', max_length=50, verbose_name='Текст кнопки корзины'),
        ),
        migrations.AlterField(
            model_name='featuredproductssettings',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показывать блок?'),
        ),
        migrations.AlterField(
            model_name='featuredproductssettings',
            name='view_all_text',
            field=models.CharField(default='Все товары →', max_length=50, verbose_name='Текст ссылки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Общая себестоимость'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Стоимость нашей доставки клиенту'),
        ),
        migrations.AlterField(
            model_name='order',
            name='gross_profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Валовая прибыль (Чистыми)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items_purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Закупочная цена товаров'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items_retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Розничная цена товаров (Выручка)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_source',
            field=models.CharField(blank=True, help_text='Для ручных заказов впишите: Instagram, Шоурум и т.д. Если заказ с сайта, заполнится само.', max_length=100, null=True, verbose_name='Откуда заказ (Источник)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='supplier_shipping_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Доставка от поставщика'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Итоговая сумма (Чек)'),
        ),
    ]
